### ISSUE TITLE
Port allows jumping on ceiling with water

### ISSUE THREAD

**Issue by velipso** [velipso/ee-offline#1]
Reported by Mochio on Discord

```
just put a block above water and jump
B
W

B: block W:water
and smiley is in water
```

[bug.eelvl.zip](https://github.com/velipso/ee-offline/files/9167924/bug.eelvl.zip)

**Comment by ghost** [comment]
i identified the cause.
the cause is because mor is int in eeo.

this.mory = _water_buoyancy;

after this code mory becomes 0 in eeo because casting from Number type to int type floors the value.

so i think u can fix this bug by changing this code

```js
case ItemId.WATER:
  this.morx = 0;
  this.mory = Config.physics_water_buoyancy;
  break;
case ItemId.MUD:
  this.morx = 0;
  this.mory = Config.physics_mud_buoyancy;
  break;
case ItemId.LAVA:
  this.morx = 0;
  this.mory = Config.physics_lava_buoyancy;
  break;
case ItemId.TOXIC_WASTE:
  this.morx = 0;
  this.mory = Config.physics_toxic_buoyancy;
```

to this

```js
case ItemId.WATER:
  this.morx = 0;
  this.mory = 0;
  break;
case ItemId.MUD:
  this.morx = 0;
  this.mory = 0;
  break;
case ItemId.LAVA:
  this.morx = 0;
  this.mory = 0;
  break;
case ItemId.TOXIC_WASTE:
  this.morx = 0;
  this.mory = 0;
```

**Comment by velipso** [comment]
ahha! thanks!

I pushed an update here:

https://sean.cm/m/ee-offline/web/index.html

is it fixed now?

commit: cc1bc8a152a33b62e2ea93dbdbaefdc1174d3f6b

**Comment by ghost** [comment]
yeah
